# Generated by Django 3.2.5 on 2023-03-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0007_alter_courserating_course_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Course Chapter model'},
        ),
        migrations.AlterModelOptions(
            name='coursepriority',
            options={'verbose_name': 'Course prioritie'},
        ),
        migrations.AlterModelOptions(
            name='courseviews',
            options={'verbose_name': 'Course view'},
        ),
        migrations.AlterModelOptions(
            name='parentcategory',
            options={'verbose_name': 'Category model'},
        ),
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'Topic model'},
        ),
        migrations.AlterField(
            model_name='recentlyviewcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
